# Generated by Django 5.2.5 on 2025-08-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0003_alter_skill_icon_alter_skill_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(default='image-upload', upload_to='photos/'),
        ),
    ]
